# Generated by Django 5.1.15 on 2026-04-05 15:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название заявки')),
                ('company_name', models.CharField(max_length=255, verbose_name='Компания')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('review', 'На рассмотрении'), ('approved', 'Подтвержден'), ('declined', 'Отклонен')], default='new', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('banner', 'Баннер'), ('poll_spot', 'Платное место в опросе'), ('sponsor', 'Спонсорский блок')], max_length=16, verbose_name='Тип размещения')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='URL баннера')),
                ('target_url', models.URLField(blank=True, verbose_name='Ссылка перехода')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активно'), ('paused', 'Приостановлено'), ('finished', 'Завершено')], default='draft', max_length=16, verbose_name='Статус')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_placements', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='charts.poll', verbose_name='Голосование')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='clients.clientcontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Рекламное размещение',
                'verbose_name_plural': 'Рекламные размещения',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.clientcontract', verbose_name='Договор')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='clients.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Позиция договора',
                'verbose_name_plural': 'Позиции договора',
                'unique_together': {('contract', 'service')},
            },
        ),
    ]
