# Generated by Django 5.1.15 on 2026-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacement',
            name='image',
            field=models.ImageField(blank=True, upload_to='placements/', verbose_name='Файл баннера'),
        ),
    ]
