from django.urls import path

from core.views import (
    AdminArtistCreateView,
    AdminArtistDeleteView,
    AdminArtistListView,
    AdminArtistUpdateView,
    AdminContractListView,
    AdminContractUpdateView,
    AdminDashboardView,
    AdminGenreCreateView,
    AdminGenreDeleteView,
    AdminGenreListView,
    AdminGenreUpdateView,
    AdminPlacementCreateView,
    AdminPlacementListView,
    AdminPlacementUpdateView,
    AdminPollCreateView,
    AdminPollDeleteView,
    AdminPollListView,
    AdminPollUpdateView,
    AdminServiceCreateView,
    AdminServiceDeleteView,
    AdminServiceListView,
    AdminServiceUpdateView,
    AdminSongCreateView,
    AdminSongDeleteView,
    AdminSongListView,
    AdminSongUpdateView,
    AdminUserListView,
    AdminUserUpdateView,
    DashboardRedirectView,
    HomeView,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("dashboard/", DashboardRedirectView.as_view(), name="dashboard-redirect"),
    path("admin-dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin-dashboard/genres/", AdminGenreListView.as_view(), name="admin-genres"),
    path("admin-dashboard/genres/new/", AdminGenreCreateView.as_view(), name="admin-genre-create"),
    path("admin-dashboard/genres/<int:pk>/edit/", AdminGenreUpdateView.as_view(), name="admin-genre-edit"),
    path("admin-dashboard/genres/<int:pk>/delete/", AdminGenreDeleteView.as_view(), name="admin-genre-delete"),
    path("admin-dashboard/artists/", AdminArtistListView.as_view(), name="admin-artists"),
    path("admin-dashboard/artists/new/", AdminArtistCreateView.as_view(), name="admin-artist-create"),
    path("admin-dashboard/artists/<int:pk>/edit/", AdminArtistUpdateView.as_view(), name="admin-artist-edit"),
    path("admin-dashboard/artists/<int:pk>/delete/", AdminArtistDeleteView.as_view(), name="admin-artist-delete"),
    path("admin-dashboard/songs/", AdminSongListView.as_view(), name="admin-songs"),
    path("admin-dashboard/songs/new/", AdminSongCreateView.as_view(), name="admin-song-create"),
    path("admin-dashboard/songs/<int:pk>/edit/", AdminSongUpdateView.as_view(), name="admin-song-edit"),
    path("admin-dashboard/songs/<int:pk>/delete/", AdminSongDeleteView.as_view(), name="admin-song-delete"),
    path("admin-dashboard/polls/", AdminPollListView.as_view(), name="admin-polls"),
    path("admin-dashboard/polls/new/", AdminPollCreateView.as_view(), name="admin-poll-create"),
    path("admin-dashboard/polls/<int:pk>/edit/", AdminPollUpdateView.as_view(), name="admin-poll-edit"),
    path("admin-dashboard/polls/<int:pk>/delete/", AdminPollDeleteView.as_view(), name="admin-poll-delete"),
    path("admin-dashboard/services/", AdminServiceListView.as_view(), name="admin-services"),
    path("admin-dashboard/services/new/", AdminServiceCreateView.as_view(), name="admin-service-create"),
    path("admin-dashboard/services/<int:pk>/edit/", AdminServiceUpdateView.as_view(), name="admin-service-edit"),
    path("admin-dashboard/services/<int:pk>/delete/", AdminServiceDeleteView.as_view(), name="admin-service-delete"),
    path("admin-dashboard/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin-dashboard/users/<int:pk>/edit/", AdminUserUpdateView.as_view(), name="admin-user-edit"),
    path("admin-dashboard/contracts/", AdminContractListView.as_view(), name="admin-contracts"),
    path("admin-dashboard/contracts/<int:pk>/edit/", AdminContractUpdateView.as_view(), name="admin-contract-edit"),
    path("admin-dashboard/placements/", AdminPlacementListView.as_view(), name="admin-placements"),
    path("admin-dashboard/placements/new/", AdminPlacementCreateView.as_view(), name="admin-placement-create"),
    path("admin-dashboard/placements/<int:pk>/edit/", AdminPlacementUpdateView.as_view(), name="admin-placement-edit"),
]
