# Generated by Django 5.1.15 on 2026-04-05 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Исполнитель')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Страна')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='charts.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ('name',),
                'unique_together': {('name', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание')),
                ('vote_for_songs', models.BooleanField(default=True, verbose_name='Голосование за песни')),
                ('vote_for_artists', models.BooleanField(default=True, verbose_name='Голосование за исполнителей')),
                ('max_song_choices', models.PositiveIntegerField(default=3, verbose_name='Максимум песен')),
                ('max_artist_choices', models.PositiveIntegerField(default=3, verbose_name='Максимум исполнителей')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='charts.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='RatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('rating_type', models.CharField(choices=[('song', 'Песни'), ('artist', 'Исполнители')], max_length=16, verbose_name='Тип рейтинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_snapshots', to='charts.genre', verbose_name='Жанр')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_snapshots', to='charts.poll', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Снимок рейтинга',
                'verbose_name_plural': 'Снимки рейтингов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('duration_seconds', models.PositiveIntegerField(default=180, verbose_name='Длительность, сек')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год релиза')),
                ('image_url', models.URLField(blank=True, verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='charts.artist', verbose_name='Исполнитель')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='charts.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ('title',),
                'unique_together': {('title', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='VoteDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('song', 'Песня'), ('artist', 'Исполнитель')], max_length=16, verbose_name='Тип голоса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_votes', to='charts.artist', verbose_name='Исполнитель')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_items', to='charts.poll', verbose_name='Голосование')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_votes', to='charts.song', verbose_name='Песня')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_draft_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Черновой голос',
                'verbose_name_plural': 'Черновые голоса',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_submissions', to='charts.poll', verbose_name='Голосование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправленный голос',
                'verbose_name_plural': 'Отправленные голоса',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='VoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('song', 'Песня'), ('artist', 'Исполнитель')], max_length=16, verbose_name='Тип голоса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_items', to='charts.artist', verbose_name='Исполнитель')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_items', to='charts.song', verbose_name='Песня')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='charts.votesubmission', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Элемент голоса',
                'verbose_name_plural': 'Элементы голосов',
            },
        ),
        migrations.CreateModel(
            name='PollArtistOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Платное размещение')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='charts.artist', verbose_name='Исполнитель')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_options', to='charts.poll', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Опция исполнителя',
                'verbose_name_plural': 'Опции исполнителей',
                'ordering': ('display_order', 'artist__name'),
                'unique_together': {('poll', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='RatingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_entries', to='charts.artist', verbose_name='Исполнитель')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='charts.ratingsnapshot', verbose_name='Снимок')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_entries', to='charts.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Позиция рейтинга',
                'verbose_name_plural': 'Позиции рейтингов',
                'ordering': ('position',),
                'unique_together': {('snapshot', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PollSongOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Платное размещение')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_options', to='charts.poll', verbose_name='Голосование')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='charts.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Опция песни',
                'verbose_name_plural': 'Опции песен',
                'ordering': ('display_order', 'song__title'),
                'unique_together': {('poll', 'song')},
            },
        ),
        migrations.AddConstraint(
            model_name='votesubmission',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='unique_submission_per_user_and_poll'),
        ),
    ]
